### ISSUE TITLE
Beinecke attributions do not match Beinecke format

### ISSUE THREAD

**Issue by GracefulLemming** [NEU-DSG/dailp-encoding#79]
For now, we could remove our boilerplate text and manually input the properly formed attribution in the metadata sheets.

Perhaps down the line we could add source collections to our data model, allowing for less manual reduplication.

**Comment by loafofpiecrust** [comment]
I thought that I followed the format that they described on their attribution page. Could you describe what you changed it to? Also, I embedded this data directly in the document metadata because we are providing the link to the specific entry in their collection. We could use an ID for the name and refer to an entry in a sources collection, but I think the URL should at least be specifiable per-document.
